CREATE TABLE  `project_flush`.`log` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`state` BOOLEAN NOT NULL ,
`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`toilet_id` INT NOT NULL
) ENGINE = MYISAM ;