#!/bin/sh
### BEGIN INIT INFO
# Provides:          flushd
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop Intracto flush daemon
### END INIT INFO

set -e

. /lib/lsb/init-functions

case $1 in
	start)
		log_daemon_msg "Starting Intracto flush daemon" "flushd"
		su - pi -c "cd /var/www && ./bash_daemon.sh &"
		echo
	;;
	stop)
		log_daemon_msg "Stopping web server" "flushd"
		killall -9 bash_daemon.sh
		echo
	;;
	*)
		log_success_msg "Usage: /etc/init.d/flushd {start|stop}"
		exit 1
	;;
esac
